# Generated by Django 2.2.13 on 2022-06-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20220611_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='nombreProducto',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='level',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Masa lista'), ('2', 'Pasa Palos')], max_length=20),
        ),
    ]
