# Generated by Django 2.2.13 on 2022-06-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20220610_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombres',
            new_name='firts_name',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellidos',
            new_name='last_name',
        ),
    ]
