# Generated by Django 2.2.13 on 2022-06-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20220610_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='firts_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
