# Generated by Django 2.2.13 on 2022-06-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20220610_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nivel',
            new_name='level',
        ),
    ]
