# Generated by Django 2.2.13 on 2022-06-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20220625_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Masa lista'), ('2', 'PasaPalos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamanio',
            field=models.CharField(choices=[('1', 'Grande empanada 560g'), ('2', 'Mediana empanada 500g'), ('3', 'Pequeña empanda 450g'), ('4', 'Grande flauta 600g'), ('5', 'Pequeña flauta 550g'), ('6', 'PasaPalos 450g')], max_length=20),
        ),
    ]
