# Generated by Django 2.2.13 on 2022-06-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20220610_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='firts_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
