# Generated by Django 2.2.13 on 2022-06-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20220611_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='firts_name',
        ),
    ]
