# Generated by Django 2.2.13 on 2022-06-25 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20220625_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idUsuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
